/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as AppWWorkspaceIdRouteRouteImport } from './routes/_app/w/$workspaceId/route'
import { Route as AppWorkspacesIndexRouteImport } from './routes/_app/workspaces/index'
import { Route as AppWorkspacesNewRouteImport } from './routes/_app/workspaces/new'
import { Route as AppWWorkspaceIdIndexRouteImport } from './routes/_app/w/$workspaceId/index'
import { Route as AppWWorkspaceIdAreaRouteImport } from './routes/_app/w/$workspaceId/$area'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWWorkspaceIdRouteRoute = AppWWorkspaceIdRouteRouteImport.update({
  id: '/w/$workspaceId',
  path: '/w/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesIndexRoute = AppWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesNewRoute = AppWorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWWorkspaceIdIndexRoute = AppWWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWWorkspaceIdRouteRoute,
} as any)
const AppWWorkspaceIdAreaRoute = AppWWorkspaceIdAreaRouteImport.update({
  id: '/$area',
  path: '/$area',
  getParentRoute: () => AppWWorkspaceIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/demo': typeof DemoRoute
  '/invite': typeof InviteRoute
  '/verify-email': typeof VerifyEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/dev/components': typeof DevComponentsRoute
  '/w/$workspaceId': typeof AppWWorkspaceIdRouteRouteWithChildren
  '/workspaces/new': typeof AppWorkspacesNewRoute
  '/workspaces/': typeof AppWorkspacesIndexRoute
  '/w/$workspaceId/$area': typeof AppWWorkspaceIdAreaRoute
  '/w/$workspaceId/': typeof AppWWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/demo': typeof DemoRoute
  '/invite': typeof InviteRoute
  '/verify-email': typeof VerifyEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/dev/components': typeof DevComponentsRoute
  '/workspaces/new': typeof AppWorkspacesNewRoute
  '/workspaces': typeof AppWorkspacesIndexRoute
  '/w/$workspaceId/$area': typeof AppWWorkspaceIdAreaRoute
  '/w/$workspaceId': typeof AppWWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/demo': typeof DemoRoute
  '/invite': typeof InviteRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/dev/components': typeof DevComponentsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/w/$workspaceId': typeof AppWWorkspaceIdRouteRouteWithChildren
  '/_app/workspaces/new': typeof AppWorkspacesNewRoute
  '/_app/workspaces/': typeof AppWorkspacesIndexRoute
  '/_app/w/$workspaceId/$area': typeof AppWWorkspaceIdAreaRoute
  '/_app/w/$workspaceId/': typeof AppWWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/invite'
    | '/verify-email'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dev/components'
    | '/w/$workspaceId'
    | '/workspaces/new'
    | '/workspaces/'
    | '/w/$workspaceId/$area'
    | '/w/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/invite'
    | '/verify-email'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dev/components'
    | '/workspaces/new'
    | '/workspaces'
    | '/w/$workspaceId/$area'
    | '/w/$workspaceId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/demo'
    | '/invite'
    | '/verify-email'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/dev/components'
    | '/_app/'
    | '/_app/w/$workspaceId'
    | '/_app/workspaces/new'
    | '/_app/workspaces/'
    | '/_app/w/$workspaceId/$area'
    | '/_app/w/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DemoRoute: typeof DemoRoute
  InviteRoute: typeof InviteRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DevComponentsRoute: typeof DevComponentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/w/$workspaceId': {
      id: '/_app/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof AppWWorkspaceIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/': {
      id: '/_app/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AppWorkspacesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/new': {
      id: '/_app/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof AppWorkspacesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workspaceId/': {
      id: '/_app/w/$workspaceId/'
      path: '/'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof AppWWorkspaceIdIndexRouteImport
      parentRoute: typeof AppWWorkspaceIdRouteRoute
    }
    '/_app/w/$workspaceId/$area': {
      id: '/_app/w/$workspaceId/$area'
      path: '/$area'
      fullPath: '/w/$workspaceId/$area'
      preLoaderRoute: typeof AppWWorkspaceIdAreaRouteImport
      parentRoute: typeof AppWWorkspaceIdRouteRoute
    }
  }
}

interface AppWWorkspaceIdRouteRouteChildren {
  AppWWorkspaceIdAreaRoute: typeof AppWWorkspaceIdAreaRoute
  AppWWorkspaceIdIndexRoute: typeof AppWWorkspaceIdIndexRoute
}

const AppWWorkspaceIdRouteRouteChildren: AppWWorkspaceIdRouteRouteChildren = {
  AppWWorkspaceIdAreaRoute: AppWWorkspaceIdAreaRoute,
  AppWWorkspaceIdIndexRoute: AppWWorkspaceIdIndexRoute,
}

const AppWWorkspaceIdRouteRouteWithChildren =
  AppWWorkspaceIdRouteRoute._addFileChildren(AppWWorkspaceIdRouteRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppWWorkspaceIdRouteRoute: typeof AppWWorkspaceIdRouteRouteWithChildren
  AppWorkspacesNewRoute: typeof AppWorkspacesNewRoute
  AppWorkspacesIndexRoute: typeof AppWorkspacesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppWWorkspaceIdRouteRoute: AppWWorkspaceIdRouteRouteWithChildren,
  AppWorkspacesNewRoute: AppWorkspacesNewRoute,
  AppWorkspacesIndexRoute: AppWorkspacesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DemoRoute: DemoRoute,
  InviteRoute: InviteRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DevComponentsRoute: DevComponentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
